services:
  bot:
    build: .
    working_dir: /app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - ALLOWED_USERS=${ALLOWED_USERS}
      - TZ=Europe/Moscow
    depends_on:
      - mysql
    restart: unless-stopped

  web:
    build: { dockerfile: Dockerfile.web }
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TZ=Europe/Moscow
    working_dir: /app
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

volumes:
  mysql-data:
